# Generated by Django 4.0.4 on 2023-06-16 14:21

from django.db import migrations, models
import what_we_are_doing.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeAreDoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_whatWeAreDoing', models.FileField(blank=True, upload_to='background/WhatWeAreDoing/', validators=[what_we_are_doing.validators.validate_image_extension])),
                ('text_WhatWeAreDoing', models.TextField(blank=True, default='', max_length=1000)),
                ('text_WhatWeAreDoing_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('text_project', models.TextField(blank=True, default='', max_length=1000)),
                ('text_project_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('image_bg_whatWeAreDoing_project', models.FileField(blank=True, upload_to='background/about/', validators=[what_we_are_doing.validators.validate_image_extension])),
                ('text_themes', models.TextField(blank=True, default='', max_length=1000)),
                ('text_themes_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
