# Generated by Django 4.0.4 on 2023-06-16 19:21

from django.db import migrations, models
import what_we_are_doing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_themes', models.FileField(blank=True, upload_to='background/themes/', validators=[what_we_are_doing.validators.validate_image_extension])),
                ('themes_icons', models.FileField(blank=True, upload_to='background/themes/', validators=[what_we_are_doing.validators.validate_image_extension])),
                ('themes_title', models.TextField(blank=True, default='', max_length=1000)),
                ('themes_title_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('themes_dsc1', models.TextField(blank=True, default='', max_length=1000)),
                ('themes_dsc1_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('themes_dsc2', models.TextField(blank=True, default='', max_length=1000)),
                ('themes_dsc2_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
