# Generated by Django 4.0.4 on 2023-06-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0002_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='themes_title',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='themes',
            name='themes_title_ar',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
