# Generated by Django 4.0.4 on 2023-06-16 19:49

from django.db import migrations, models
import what_we_are_doing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0003_alter_themes_themes_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='themes_details_image',
            field=models.FileField(blank=True, upload_to='background/themes/', validators=[what_we_are_doing.validators.validate_image_extension]),
        ),
    ]
