# Generated by Django 4.0.4 on 2023-06-20 18:58

from django.db import migrations, models
import what_we_are_doing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0004_themes_themes_details_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_theme', models.FileField(blank=True, upload_to='background/WhatWeAreDoing/', validators=[what_we_are_doing.validators.validate_image_extension])),
            ],
        ),
    ]
