# Generated by Django 4.0.4 on 2023-06-21 19:03

import datetime
from django.db import migrations, models
import what_we_are_doing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0005_themebackgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.FileField(blank=True, upload_to='background/themes/', validators=[what_we_are_doing.validators.validate_image_extension])),
                ('project_name', models.CharField(blank=True, default='', max_length=1000)),
                ('project_name_ar', models.CharField(blank=True, default='', max_length=1000)),
                ('project_date', models.DateField(blank=True, default=datetime.date.today)),
                ('project_location', models.CharField(blank=True, default='', max_length=300)),
                ('project_location_ar', models.CharField(blank=True, default='', max_length=300)),
                ('project_parteners', models.CharField(blank=True, default='', max_length=1000)),
                ('project_parteners_ar', models.CharField(blank=True, default='', max_length=1000)),
                ('project_dsc1', models.TextField(blank=True, default='', max_length=1000)),
                ('project_dsc1_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
            ],
        ),
    ]
