# Generated by Django 4.0.4 on 2023-06-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0006_project_projectcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCategory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='what_we_are_doing.category'),
        ),
    ]
