# Generated by Django 4.2.2 on 2023-06-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0007_rename_projectcategory_category_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
