# Generated by Django 4.0.4 on 2023-06-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0007_rename_projectcategory_category_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='image_bg_themes',
        ),
    ]
