# Generated by Django 4.0.4 on 2023-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0008_remove_themes_image_bg_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
