# Generated by Django 4.0.4 on 2023-07-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0009_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dr_name',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_dsc1_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='project_location_dr',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_dr',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='project_parteners_dr',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='themes',
            name='themes_dsc1_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='themes',
            name='themes_dsc2_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='themes',
            name='themes_title_dr',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whatwearedoing',
            name='text_WhatWeAreDoing_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whatwearedoing',
            name='text_project_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='whatwearedoing',
            name='text_themes_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
