# Generated by Django 4.0.4 on 2023-07-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0008_alter_themes_id'),
        ('what_we_are_doing', '0010_category_dr_name_project_project_dsc1_dr_and_more'),
    ]

    operations = [
    ]
