# Generated by Django 4.0.4 on 2023-07-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_are_doing', '0011_merge_20230709_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
