# Generated by Django 4.0.4 on 2023-06-17 21:49

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_about_index', models.TextField(blank=True, default='', max_length=1000)),
                ('text_about_index_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('num_employee_index', models.CharField(blank=True, default='', max_length=1000)),
                ('num_project_index', models.CharField(blank=True, default='', max_length=1000)),
                ('num_benefi_index', models.CharField(blank=True, default='', max_length=1000)),
                ('num_volunteer_index', models.CharField(blank=True, default='', max_length=1000)),
                ('image_story_index', models.FileField(blank=True, upload_to='background/index/', validators=[home.validators.validate_image_extension])),
                ('text_story_index', models.TextField(blank=True, default='', max_length=1000)),
                ('text_story_index_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_text', models.TextField(blank=True, default='', max_length=1000)),
                ('whatDoDetail_text_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image_index', models.FileField(blank=True, upload_to='background/index/', validators=[home.validators.validate_image_extension])),
                ('slide_title_index', models.CharField(blank=True, default='', max_length=300)),
                ('slide_title_index_ar', models.CharField(blank=True, default='', max_length=300)),
                ('slide_subtitle_index', models.CharField(blank=True, default='', max_length=300)),
                ('slide_subtitle_index_ar', models.CharField(blank=True, default='', max_length=300)),
                ('slide_dsc_index', models.CharField(blank=True, default='', max_length=300)),
                ('slide_dsc_index_ar', models.CharField(blank=True, default='', max_length=300)),
                ('slide_num_index', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
