# Generated by Django 4.0.4 on 2023-06-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slide_dsc_index',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slide_dsc_index_ar',
        ),
    ]
