# Generated by Django 4.0.4 on 2023-06-17 10:14

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_Core', models.FileField(upload_to='background/about/', validators=[about.validators.validate_image_extension])),
                ('core_name', models.TextField(blank=True, default='', max_length=1000)),
                ('core_name_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('core_image', models.FileField(upload_to='background/about/', validators=[about.validators.validate_image_extension])),
                ('core_position', models.CharField(blank=True, default='', max_length=1000)),
                ('core_position_ar', models.CharField(blank=True, default='', max_length=1000)),
                ('core_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('core_desc_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_goals', models.FileField(upload_to='background/about/', validators=[about.validators.validate_image_extension])),
                ('text_goals', models.TextField(blank=True, default='', max_length=1000)),
                ('text_goals_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('text_title', models.CharField(blank=True, default='', max_length=1000)),
                ('text_title_ar', models.CharField(blank=True, default='', max_length=1000)),
                ('goal_num', models.TextField(blank=True, default='', max_length=1000)),
                ('goal_num_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('goal_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('goal_desc_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_history', models.FileField(upload_to='background/about/', validators=[about.validators.validate_image_extension])),
                ('text_history', models.TextField(blank=True, default='', max_length=1000)),
                ('text_history_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('text_history1', models.TextField(blank=True, default='', max_length=1000)),
                ('text_history1_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('text_history2', models.TextField(blank=True, default='', max_length=1000)),
                ('text_history2_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_internal_system', models.FileField(upload_to='background/InternalSystem/', validators=[about.validators.validate_image_extension])),
                ('interanl_system_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('interanl_system_desc_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PartenerNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_partener_network', models.FileField(upload_to='background/PartenerNetwork/', validators=[about.validators.validate_image_extension])),
                ('partener_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('partener_desc_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('network_desc', models.CharField(blank=True, default='', max_length=1000)),
                ('network_desc_ar', models.CharField(blank=True, default='', max_length=1000)),
                ('logo1', models.FileField(upload_to='background/PartenerNetwork/', validators=[about.validators.validate_image_extension])),
                ('logo2', models.FileField(upload_to='background/PartenerNetwork/', validators=[about.validators.validate_image_extension])),
                ('logo3', models.FileField(upload_to='background/PartenerNetwork/', validators=[about.validators.validate_image_extension])),
                ('logo4', models.FileField(upload_to='background/PartenerNetwork/', validators=[about.validators.validate_image_extension])),
                ('logo5', models.FileField(upload_to='background/PartenerNetwork/', validators=[about.validators.validate_image_extension])),
                ('logo6', models.FileField(upload_to='background/PartenerNetwork/', validators=[about.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='VisionMissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_vission_mission', models.FileField(upload_to='background/vission_mission/', validators=[about.validators.validate_image_extension])),
                ('Vission_Mission_Value_desc1', models.TextField(blank=True, default='', max_length=300)),
                ('Vission_Mission_Value_desc1_ar', models.TextField(blank=True, default='', max_length=300)),
                ('Vission_desc', models.TextField(blank=True, default='', max_length=300)),
                ('Vission_desc_ar', models.TextField(blank=True, default='', max_length=300)),
                ('mission_desc', models.TextField(blank=True, default='', max_length=300)),
                ('mission_desc_ar', models.TextField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
