# Generated by Django 4.0.4 on 2023-06-17 11:14

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_about', models.FileField(upload_to='background/vission_mission/', validators=[about.validators.validate_image_extension])),
                ('textabout_desc1', models.TextField(blank=True, default='', max_length=1000)),
                ('textabout_desc1_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('textabout_desc2', models.TextField(blank=True, default='', max_length=1000)),
                ('textabout_desc2_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='goals',
            name='goal_num_ar',
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_desc',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='Vission_Mission_Value_desc1',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='Vission_Mission_Value_desc1_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='Vission_desc',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='Vission_desc_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='mission_desc',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='visionmissionvalue',
            name='mission_desc_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
