# Generated by Django 4.0.4 on 2023-06-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_goals_image_banner_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='text_title',
            new_name='goal_name',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='text_title_ar',
            new_name='goal_name_ar',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='text_goals',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='text_goals_ar',
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_desc',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_num',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
