# Generated by Django 4.0.4 on 2023-06-17 13:03

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_rename_text_title_goals_goal_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereWeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_where_we_work', models.FileField(upload_to='background/WhereWeWork/', validators=[about.validators.validate_image_extension])),
            ],
        ),
    ]
