# Generated by Django 4.0.4 on 2023-06-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_wherewework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='image_banner_Core',
        ),
        migrations.AlterField(
            model_name='core',
            name='core_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='core',
            name='core_name_ar',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
