# Generated by Django 4.0.4 on 2023-06-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_core_image_banner_core_alter_core_core_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='GoalList',
        ),
    ]
