# Generated by Django 4.0.4 on 2023-06-17 14:45

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_rename_goals_goallist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_goal', models.FileField(upload_to='background/about/', validators=[about.validators.validate_image_extension])),
                ('goal_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('goal_desc_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
