# Generated by Django 4.0.4 on 2023-06-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionmissionvalue',
            name='Vission_Mission_Value_desc1',
        ),
        migrations.RemoveField(
            model_name='visionmissionvalue',
            name='Vission_Mission_Value_desc1_ar',
        ),
    ]
