# Generated by Django 4.0.4 on 2023-06-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_remove_visionmissionvalue_vission_mission_value_desc1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenernetwork',
            name='logo1',
        ),
        migrations.RemoveField(
            model_name='partenernetwork',
            name='logo2',
        ),
        migrations.RemoveField(
            model_name='partenernetwork',
            name='logo3',
        ),
        migrations.RemoveField(
            model_name='partenernetwork',
            name='logo4',
        ),
        migrations.RemoveField(
            model_name='partenernetwork',
            name='logo5',
        ),
        migrations.RemoveField(
            model_name='partenernetwork',
            name='logo6',
        ),
    ]
