# Generated by Django 4.0.4 on 2023-06-28 14:26

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_remove_partenernetwork_logo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartenerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_partener', models.FileField(upload_to='background/PartenerNetwork/', validators=[about.validators.validate_image_extension])),
            ],
        ),
    ]
