# Generated by Django 4.0.4 on 2023-06-30 10:03

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_internalsystemlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrassRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_grassRoot', models.FileField(upload_to='background/InternalSystem/', validators=[about.validators.validate_image_extension])),
                ('grassRoot_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('grassRoot_desc_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
