# Generated by Django 4.0.4 on 2023-06-30 11:24

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_academics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner_capacity', models.FileField(upload_to='background/about/', validators=[about.validators.validate_image_extension])),
                ('capacity_desc', models.TextField(blank=True, default='', max_length=1000)),
                ('capacity_desc_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('capacity_desc1', models.TextField(blank=True, default='', max_length=1000)),
                ('capacity_desc1_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CapacityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_list', models.CharField(blank=True, default='', max_length=1000)),
                ('capacity_list_ar', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
