# Generated by Django 4.0.4 on 2023-07-01 15:43

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_capacity_capacitylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreBgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_core', models.FileField(upload_to='background/vission_mission/', validators=[about.validators.validate_image_extension])),
                ('textcore_desc1', models.TextField(blank=True, default='', max_length=1000)),
                ('textcore_desc1_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
