# Generated by Django 4.0.4 on 2023-07-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_corebgimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='textabout_desc1_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='about',
            name='textabout_desc2_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='capacity',
            name='capacity_desc1_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='capacity',
            name='capacity_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='capacitylist',
            name='capacity_list_dr',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='core',
            name='core_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='core',
            name='core_name_dr',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='core',
            name='core_position_dr',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='corebgimage',
            name='textcore_desc1_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='goallist',
            name='goal_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='goallist',
            name='goal_name_dr',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='history',
            name='text_history1_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='history',
            name='text_history2_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='history',
            name='text_history_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='partenernetwork',
            name='network_desc_dr',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='partenernetwork',
            name='partener_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='visionmissionvalue',
            name='Vission_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='visionmissionvalue',
            name='mission_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
