# Generated by Django 4.0.4 on 2023-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_about_textabout_desc1_dr_about_textabout_desc2_dr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalsystemlist',
            name='internal_list_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
