# Generated by Django 4.0.4 on 2023-07-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_internalsystemlist_internal_list_dr'),
    ]

    operations = [
        migrations.AddField(
            model_name='grassroot',
            name='grassRoot_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
