# Generated by Django 4.0.4 on 2023-07-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_grassroot_grassroot_desc_dr'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='academics_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='internalsystem',
            name='interanl_system_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
