# Generated by Django 4.0.4 on 2023-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_academics_academics_desc_dr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodology_list', models.CharField(blank=True, default='', max_length=1000)),
                ('methodology_list_ar', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
