# Generated by Django 4.0.4 on 2023-07-12 14:52

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_methodology_methodology_list_dr'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodology_list', models.CharField(blank=True, default='', max_length=1000)),
                ('methodology_list_ar', models.CharField(blank=True, default='', max_length=1000)),
                ('methodology_list_dr', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='methodology_list',
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='methodology_list_ar',
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='methodology_list_dr',
        ),
        migrations.AddField(
            model_name='methodology',
            name='image_banner_methodology',
            field=models.FileField(default=3, upload_to='background/about/', validators=[about.validators.validate_image_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodology',
            name='methodology_desc',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='methodology',
            name='methodology_desc_ar',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='methodology',
            name='methodology_desc_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
