# Generated by Django 4.0.4 on 2023-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0024_remove_wherewework_image_banner_where_we_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wherewework',
            name='governorate',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wherewework',
            name='governorate_ar',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wherewework',
            name='governorate_dr',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
