# Generated by Django 4.0.4 on 2023-07-29 12:13

import about.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0026_alter_wherewework_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereWeWorkBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_where_we_work', models.FileField(upload_to='background/about/', validators=[about.validators.validate_image_extension])),
            ],
        ),
    ]
