# Generated by Django 4.0.4 on 2023-06-17 19:50

from django.db import migrations, models
import get_involved.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetInvolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_get_involved', models.FileField(blank=True, null=True, upload_to='background/GetInvolved/', validators=[get_involved.validators.validate_image_extension])),
                ('career_text', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('career_text_ar', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('Volunteers_text', models.TextField(blank=True, null=True)),
                ('Volunteers_text_ar', models.TextField(blank=True, null=True)),
                ('Donate_text', models.TextField(blank=True, null=True)),
                ('Donate_text_ar', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
