# Generated by Django 4.0.4 on 2023-06-17 20:20

from django.db import migrations, models
import get_involved.validators


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_volunteer', models.FileField(upload_to='background/volunteer/', validators=[get_involved.validators.validate_image_extension])),
            ],
        ),
    ]
