# Generated by Django 4.0.4 on 2023-06-17 21:03

from django.db import migrations, models
import get_involved.validators


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0005_alter_donate_image_bg_donate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('career_name_ar', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('career_employee_type', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('career_employee_type_ar', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('career_summary_text', models.TextField(blank=True, null=True)),
                ('career_summary_text_ar', models.TextField(blank=True, null=True)),
                ('career_duties_text', models.TextField(blank=True, null=True)),
                ('career_duties_text_ar', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=1, null=True)),
                ('job_type_ar', models.CharField(blank=True, choices=[('1', 'دوام كامل'), ('2', 'دوام جزئي'), ('3', 'تدريب')], max_length=1, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('location_ar', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('no_of_jobs', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('duties_1', models.TextField(blank=True, null=True)),
                ('duties_1_ar', models.TextField(blank=True, null=True)),
                ('duties_2', models.TextField(blank=True, null=True)),
                ('duties_2_ar', models.TextField(blank=True, null=True)),
                ('duties_3', models.TextField(blank=True, null=True)),
                ('duties_3_ar', models.TextField(blank=True, null=True)),
                ('duties_4', models.TextField(blank=True, null=True)),
                ('duties_4_ar', models.TextField(blank=True, null=True)),
                ('duties_5', models.TextField(blank=True, null=True)),
                ('duties_5_ar', models.TextField(blank=True, null=True)),
                ('skill_1', models.TextField(blank=True, null=True)),
                ('skill_1_ar', models.TextField(blank=True, null=True)),
                ('skill_2', models.TextField(blank=True, null=True)),
                ('skill_2_ar', models.TextField(blank=True, null=True)),
                ('skill_3', models.TextField(blank=True, null=True)),
                ('skill_3_ar', models.TextField(blank=True, null=True)),
                ('skill_4', models.TextField(blank=True, null=True)),
                ('skill_4_ar', models.TextField(blank=True, null=True)),
                ('skill_5', models.TextField(blank=True, null=True)),
                ('skill_5_ar', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_career_list', models.FileField(blank=True, null=True, upload_to='background/career_list/', validators=[get_involved.validators.validate_image_extension])),
            ],
        ),
    ]
