# Generated by Django 4.0.4 on 2023-07-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0008_alter_careerdetail_id'),
        ('get_involved', '0008_rename_duties_4_careerdetail_career_duties_text_dr_and_more'),
    ]

    operations = [
    ]
