# Generated by Django 4.0.4 on 2023-07-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0009_merge_20230709_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
