# Generated by Django 4.0.4 on 2023-06-18 18:50

import datetime
from django.db import migrations, models
import mediapage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image_story', models.FileField(blank=True, default='', upload_to='background/story/', validators=[mediapage.validators.validate_image_extension])),
            ],
        ),
        migrations.CreateModel(
            name='MediaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_image', models.FileField(blank=True, default='', upload_to='background/media/', validators=[mediapage.validators.validate_image_extension])),
                ('media_date', models.DateField(blank=True, default=datetime.date.today)),
                ('media_location', models.CharField(blank=True, default='', max_length=300)),
                ('media_location_ar', models.CharField(blank=True, default='', max_length=300)),
                ('media_name', models.CharField(blank=True, default='', max_length=300)),
                ('media_name_ar', models.CharField(blank=True, default='', max_length=300)),
                ('media_category', models.CharField(blank=True, default='', max_length=300)),
                ('media_category_ar', models.CharField(blank=True, default='', max_length=300)),
                ('media_desc1', models.CharField(blank=True, default='', max_length=120)),
                ('media_desc1_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('media_desc2', models.CharField(blank=True, default='', max_length=120)),
                ('media_desc2_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('media_desc3', models.CharField(blank=True, default='', max_length=120)),
                ('media_desc3_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ['-media_date'],
            },
        ),
    ]
