# Generated by Django 4.0.4 on 2023-06-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetail',
            name='media_desc1',
            field=models.TextField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='mediadetail',
            name='media_desc2',
            field=models.TextField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='mediadetail',
            name='media_desc3',
            field=models.TextField(blank=True, default='', max_length=120),
        ),
    ]
