# Generated by Django 4.0.4 on 2023-06-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediapage', '0002_alter_mediadetail_media_desc1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mediadetail',
            name='media_category',
        ),
        migrations.RemoveField(
            model_name='mediadetail',
            name='media_category_ar',
        ),
        migrations.AddField(
            model_name='mediadetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediapage.category'),
        ),
    ]
