# Generated by Django 4.0.4 on 2023-06-18 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapage', '0003_category_remove_mediadetail_media_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediadetail',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='mediadetail',
            old_name='media_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='mediadetail',
            name='views',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
