# Generated by Django 4.0.4 on 2023-06-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapage', '0004_alter_mediadetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediadetail',
            name='media_desc2',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mediadetail',
            name='media_desc3',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
