# Generated by Django 4.0.4 on 2023-07-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapage', '0006_alter_mediadetail_media_desc1'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dr_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
