# Generated by Django 4.0.4 on 2023-07-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediapage', '0007_category_dr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadetail',
            name='media_desc1_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mediadetail',
            name='media_desc2_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mediadetail',
            name='media_desc3_dr',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mediadetail',
            name='media_location_dr',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='mediadetail',
            name='media_name_dr',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
